function [DDSDDE,STRESS,STATEV,PNEW]=UMAT(DELTAEPSMATRIX,STRESSOLD,STATEV,PROPS)
%MATERIAL ROUTINE; FORMULATED SIMILAR TO ABAQUS ROUTINE UMAT


% NUMBERS (FLOATS) AS DEFINED LATER IN FORTRAN
ZERO_R=0.0;
ONE_R=1.0;
TWO_R=2.0;
THREE_R=3.0;
FOUR_R=4.0;
FIVE_R=5.0;
SIX_R=6.0;
SEVEN_R=7.0;
EIGHT_R=8.0;
NINE_R=9.0;
TEN_R=10.0;
%%	MATERIAL PARAMETERS (E-YOUNGS MODULUS; )
	E           =PROPS(1);
	NU          =PROPS(2);

%
%	SHEAR MODULUS
	G           = E/(TWO_R*(ONE_R+NU));
    
%% DIMENSION OF STRAIN/STRESS TENSOR UTILIZING SYMMETRY
NTENS   =6;

%% NORMAL COMPONENTS
NDI     =3;


%% ISOTROPIC STIFFNESS TENSOR CIJKL AS MATRIX
	CIJKL 	=zeros(6,6);
    for i=1:NTENS
        for j=1:NTENS
            if i<=NDI && j<=NDI && i~=j
				CIJKL(i,j)	=(E/(ONE_R+NU)*(NU/(ONE_R-TWO_R*NU)));
            else
				CIJKL(i,j)	=ZERO_R;
            end
        end
        if i<=NDI
			CIJKL(i,i)	=(E/(ONE_R+NU)*(ONE_R+NU/(ONE_R-TWO_R*NU)));
        else
			CIJKL(i,i)  	=TWO_R*G;
        end
    end

%% MATERIAL TANGENT DDSDDE	 AND STRESS
    
    DDSDDE		 =CIJKL;
    STRESS       =STRESSOLD+CIJKL*DELTAEPSMATRIX;

%% CONTROL VARIABLE; HERE ALWAYS 0; BECAUSE OF LINEAR ELASTICITY
    PNEW =0;

%
        
end
